platform :ios, '9.0'
inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

target 'oc-quick-start' do
  
	pod 'AFNetworking', '~> 4.0.1'
	pod 'YYKit', '~> 1.0.9'
  pod 'SVProgressHUD', '~> 2.2.5'

  
end
